language: node_js
node_js: stable
# assign build branches
branches:
  only:
    - blog-source
# cache this directory
cache:
  apt: true
  directories:
    - node_modules
# S: Build Lifecycle

before_install:
  - export TZ='Asia/Shanghai'
  
install:
  - npm install 
  
script:
  - hexo clean
  - hexo generate
  
after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout blog-source
  - cd ../
  - mv .deploy_git/.git/ ./public/  
  - cd ./public
  - git config user.name "anotherten"  
  - git config user.email "15086799777@139.com" 
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master
  
env:
 global:
  - GH_REF: github.com/anotherten/anotherten.github.io.git